CREATE DATABASE IF NOT EXISTS week1;
USE week1;

CREATE TABLE IF NOT EXISTS `demo` (
    `id` INT(20) AUTO_INCREMENT,
    `name` VARCHAR(20),
    `type` VARCHAR(20),
    `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);